development: &default
  adapter: postgresql
  encoding: unicode
  database: onadons_development
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: onandons_test

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: onandons_production
